apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-prod-blue-green-destination
spec:
  host: {{ .Values.ServiceName }}  
  subsets:
  - name: v1
    labels: 
     version: {{ .Values.blueServicelabel }}  
  - name: v2
    labels: 
     version: {{ .Values.greenServicelabel }}  
     

